### ISSUE TITLE
Rechazado.

### ISSUE THREAD

**Issue by t0kyolover** [4GeeksAcademy/i-lema-exercise-unit-test-with-jest#1]
- [x] En app.js la lógica de las funciones no es la requerida, tienes que usar la variable, como indican las instrucciones
`
let oneEuroIs = {
"JPY": 156.5,
"USD": 1.07,
"GBP": 0.87,
}`
- [x] Después de implementar las funciones correctas, verificar la lógica de los tests
- [x] Ojo que en tests tienes varias variables declaradas sin usar

** _Si sigues las instrucciones de learnpack paso a paso, los puntos de arriba se resolverán solos_ **

**Comment by i-lema** [comment]
Issues resueltos. En la parte de app.js enlacé primero utilizando la lógica de la función que me has mandado, de todos modos debajo he dejado comentado resolviendo de otra forma porque es como aparecía en el ejemplo del learnpack.
Ambas formas me pasan los test de manera correcta.
Y resolví ya lo de las variables sin usar, fue porque el ejemplo que ponía en el learnpack llevaba ya importada la función dentro del mismo test, pero yo prefería importarlas todas juntas arriba para simplificar y me quedó llamada dentro del test y no se usaba la importación de arriba. Ahora ya la borré de dentro de los test.

**Comment by t0kyolover** [comment]
De la manera que sugiere el learnpack, es dinámica, concorde con las mejores prácticas (Imaginate con muchas líneas de código, de esa manera solo cambiarías los valores de cambio de moneda dentro de la variable, sin tocar las funciones)
